"""initial migration

Revision ID: 164fbe7997a2
Revises: None
Create Date: 2015-05-29 00:35:58.786955

"""

# revision identifiers, used by Alembic.
revision = '164fbe7997a2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
