"""adding mag_section field

Revision ID: 57e8d580118
Revises: 164fbe7997a2
Create Date: 2015-05-29 00:58:23.362113

"""

# revision identifiers, used by Alembic.
revision = '57e8d580118'
down_revision = '164fbe7997a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('mag_section', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'mag_section')
    ### end Alembic commands ###
